#!/usr/bin/env bash
# This script displays information about subdomains

domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    domain_info "$1" "$2"
fi
