#!/usr/bin/env bash
# This script checks if the load balancer is listening on port 443 and accepting HTTPS traffic

check_lb () {
    response_code=$(curl -s -o /dev/null -w "%{http_code}" https://"$1")
    if [ "$response_code" == "200" ]; then
        echo "Load balancer is listening on port 443 and accepting HTTPS traffic"
    else
        echo "Load balancer is not listening on port 443 or not accepting HTTPS traffic"
    fi
}

check_lb "$1"
