#!/usr/bin/env bash
# Configures an Ubuntu machine with nginx and custom HTTP response headers

FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

STRING="Hello World!"
FOUR="Ceci n'est pas une page"

# Update packages and install nginx
apt-get -y update
apt-get -y install nginx

# Allow HTTP traffic through the firewall
ufw allow 'Nginx HTTP'

# Create index page with content
echo "$STRING" > /var/www/html/index.nginx-debian.html

# Add redirection configuration
sed -i "37i\ $REDIRECT" "$FILE"

# Add custom error page configuration
echo "$FOUR" > "$ERRORFILE"
sed -i "37i\ $ERRORREDIRECT" "$FILE"

# Add custom header configuration
sed -i "37i\ $CUSTOMHEADER" "$FILE"

# Restart nginx service to apply changes
service nginx restart
