#!/usr/bin/env bash
# A bash script to safely install HAProxy on an Ubuntu web server.

set -e  # Exit immediately if a command fails

# Install necessary packages
sudo apt update
sudo apt install --no-install-recommends -y software-properties-common

# Add HAProxy PPA to the software sources
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt update

# Install HAProxy 2.4
sudo apt install -y haproxy=2.4.*

# Restart HAProxy service
sudo systemctl restart haproxy

# Check HAProxy status
sudo systemctl status haproxy
