#!/bin/bash

# Init script to manage manage_my_process

# Define the path to the manage_my_process script
MANAGE_SCRIPT="./manage_my_process"

# Define the path to the PID file
PID_FILE="/var/run/my_process.pid"

# Function to start the manage_my_process script
start() {
  $MANAGE_SCRIPT &
  echo $! > $PID_FILE
  echo "manage_my_process started"
}

# Function to stop the manage_my_process script
stop() {
  if [ -e $PID_FILE ]; then
    kill $(cat $PID_FILE)
    rm $PID_FILE
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running"
  fi
}

# Function to restart the manage_my_process script
restart() {
  stop
  start
  echo "manage_my_process restarted"
}

# Check the argument provided
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
