#!/usr/bin/env bash
# This script kills the 7-highlander process

# Get the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send a termination signal to the process
    kill -TERM "$pid"
else
    echo "Process not found"
fi
