#!/usr/bin/env bash
# This script indefinitely writes "I am alive!" to /tmp/my_process
# Pauses for 2 seconds between messages

while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
