#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data

# Using awk to group and count occurrences, then sorting by the number of occurrences in descending order
awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
