#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables
hour=0

# Using a while loop to display hours and minutes
while [ $hour -lt 13 ]; do
    echo "Hour: $hour"
    
    minute=1
    while [ $minute -lt 60 ]; do
        echo $minute
        ((minute+=1))
    done

    ((hour+=1))
done
