#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Use the 'ip' command to show IPv4 addresses, then use 'awk' and 'cut' to extract and display only the addresses
ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
